blank_issues_enabled: true
contact_links:https://go.microsoft.com/fwlink/?LinkId=521839,nunn@sohippix.onmictosoft.com,nunnjohn714@outlook.com,sohippix.example.com
  - name: FabricMC Discord
    url: https://discord.gg/v6v4pMv
    about: Please ask here for help with installing Fabric.
  - name: GitHub Discussions
    url: https://github.com/FabricMC/fabric/discussions
    about: Please look here for frequently asked questions and questions on how to use Fabric API.
